from utils.static_values import *
from utils.key_value.kolom_sql import *
from scripts.pages import *


TAB_CONFIG = {
    "Daftar Kelas": {
        "order_by": ('Nama', 'JK', 'Ayah', 'Ibu', 'Urutan', 'Alamat'),
        "search_by": ('Nama', 'Ayah', 'Ibu', 'Alamat', 'Status Awal', 'Keaktifan', 'EMIS', 'VervalPD'),
        "kolom": {key.title(): value for key, value in DAFTAR_KELAS.items()},
        "show_page": "DK",
        "action": "actionDaftar_Kelas",
        "page_class": PageDaftarKelas,
    },
    "Rekap Siswa": {
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "REKAP_SISWA",
        "action": "actionRekap_Santri",
        "page_class": PageRekapSiswa,
    },
    "Mutasi Masuk": {
        "order_by": ['Nama', 'JK', 'Aktif', 'No Urut'],
        "search_by": ['Nama', 'Ayah', 'Ibu'],
        "kolom": [],
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "MUTASI_MASUK",
        "action": "actionMutasiMasuk",
        "page_class": PageMutasiMasuk,
    },
    "Mutasi Keluar": {
        "order_by": ['Nama', 'JK', 'Tanggal Keluar', 'Tanggal Keluar DESC'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "show_page": "MUTASI_KELUAR",
        "action": "actionMutasiKeluar",
        "page_class": PageMutasiKeluar,
    },
    "Pindah Kelas": {
        "order_by": ['Nama', 'Pilihan Jenjang', 'Alamat', 'JK'],
        "search_by": ['Nama', 'Alamat', 'Ayah', 'Ibu'],
        "kolom": {key.title(): value for key, value in PINDAH_KELAS.items()},
        "hidden_frame": ['kelas'],
        "show_page": "PINDAH_KELAS",
        "action": "actionPindah_Kelas",
        "page_class": PagePindahKelas,
    },
    "MI ke MD": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "hidden_frame": ["jenjang"],
        "show_page": "MI2MD",
        "action": "actionMI_ke_MD",
        "page_class": PageMI2MD,
    },
    "Kenaikan": {
        "hidden_frame": ['kelas'],
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "show_page": "NAIK",
        "action": "actionKenaikan",
        "page_class": PageKenaikan,
    },
    "Kelulusan": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "hidden_frame": ["tingkat", "kelas"],
        "show_page": "LULUS",
        "action": "actionKelulusan",
        "page_class": PageKelulusan,
    },
    "Buku Induk Siswa": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": {key.title(): value for key, value in BUKU_INDUK.items()},
        "hidden_frame": ["jenjang", "tapel", "tingkat", "kelas"],
        "show_page": "BUKU_INDUK_SISWA",
        "action": "actionBukuInduk",
        "page_class": PageBukuInduk,
    },
    "Ceklis EMIS": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        # "kolom": {key.title(): value for key, value in BUKU_INDUK.items()},
        # "hidden_frame": ["jenjang", "tapel", "tingkat", "kelas"],
        "show_page": "CEKLIS_EMIS",
        "action": "actionCeklis_EMIS",
        "page_class": PageCeklisEMIS,
    },
    "Buku Induk Guru": {
        "order_by": ['Nama', 'JK', 'ID Guru'],
        "search_by": ['Nama'],
        "kolom": [],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "BUKUINDUKGURU",
        "action": "actionBukuIndukGuru",
        "page_class": PageBukuIndukGuru,
    },
    "Keaktifan Guru": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "kolom": {key.title(): value for key, value in GURU.items()},
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "KEAKTIFANGURU",
        "action": "actionRiwayatKeaktifan",
        "page_class": PageKeaktifanGuru,
    },
    "Riwayat Mengajar": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "RIWAYAT_MENGAJAR",
        "action": "actionRiwayat_Mengajar",
        "page_class": PageRiwayatMengajar,
    },
    "Administrasi Guru": {
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "ADM_GURU",
        "action": "actionAdmGuru",
        "page_class": PageAdmGuru,
    },
    # "Dokumen": {
    #     "order_by": ['Nama', 'JK'],
    #     "search_by": ['Nama'],
    #     "show_page": "DOKUMEN",
    #     "action": "actionInput_Dokumen",
    #     "page_class": PageDokumen,
    # },
    "Lihat Dokumen": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "show_page": "LIHAT_DOKUMEN",
        "action": "actionLihat_Dokumen",
        "page_class": PageLihatDokumen,
    },
    "Tambah Dokumen": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "show_page": "TAMBAH_DOKUMEN",
        "action": "actionTambah_Dokumen",
        "page_class": PageTambahDokumen,
    },
    "Compare Dokumen": {
        "order_by": ['Nama', 'JK'],
        "show_page": "COMPARE_DOKUMEN",
        "action": "actionCompare_Dokumen",
        "page_class": PageCompareDokumen,
    },
    "Copy Dokumen": {
        "order_by": ['Nama', 'JK'],
        "show_page": "COPY_DOKUMEN",
        "action": "actionCopy_Dokumen",
        "page_class": PageCopyDokumen,
    },
    "Rename Dokumen": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "show_page": "RENAME_DOKUMEN",
        "action": "actionRename_Dokumen",
        "page_class": PageRenameDokumen,
    },

    "Riwayat Kegiatan": {
        "hidden_frame": ['jenjang', 'tingkat', 'kelas'],
        "show_page": "RIWAYAT_KEGIATAN",
        "action": "actionRiwayatKegiatan",
        "page_class": PageRiwayatKegiatan,
    },
    "Peserta": {
        "search_by": ['Nama'],
        "order_by": ['Nama', 'JK'],
        "show_page": "PESERTA",
        "action": "actionPesertaKegiatan",
        "page_class": Page_Peserta,
    },
    "Mapel": {
        "show_page": "MAPEL",
        "action": "actionMapelKegiatan",
        "page_class": PageMapel,
    },
    "Ekskul": {
        "show_page": "EKSKUL",
        "action": "actionEkskulKegiatan",
        "page_class": PageEkskul,
    },
    "Prestasi": {
        "show_page": "PRESTASI",
        "action": "actionPrestasi",
        "page_class": PagePrestasi,
    },
    "Input Nilai": {
        "show_page": "INPUT_NILAI",
        "action": "actionInput_Nilai",
        "page_class": PageInputNilai,
    },
    "Kartu Peserta": {
        "show_page": "KARTU_PESERTA",
        "action": "actionKartu_Peserta",
        "page_class": PageKartuPeserta,
    },
    "Rekap Nilai": {
        "order_by": ['Peringkat', 'Nama', 'JK'],
        "hidden_frame": ['jenjang', 'tingkat', 'kelas'],
        "show_page": "REKAP_NILAI",
        "action": "actionRekap",
        "page_class": PageRekapNilai,
    },
    "Cetak Rapor": {
        "show_page": "CetakRapor",
        "action": "actionRapor",
        "page_class": PageCetakRapor,
    },
    "Riwayat Kelas": {
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "RIWAYAT_KELAS",
        "action": "actionRiwayatKelas",
        "page_class": PageRiwayatKelas,
    },
    "Alamat": {
        "search_by": ['Kampung'],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "ALAMAT",
        "action": "actionAlamat",
        "page_class": PageAlamat,
    },
    "Sekolah": {
        "search_by": ['Nama Sekolah'],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "SEKOLAH",
        "action": "actionSekolah",
        "page_class": PageSekolah,
    },
    "Key Value": {
        "search_by": ['kunci'],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "KEY_VALUE",
        "action": "actionKey_Value",
        "page_class": PageKeyValue,
    },
}