from utils.static_values import *
from utils.key_value.kolom_sql import *
from scripts import *


TAB_CONFIG = {
    "Daftar Kelas": {
        "order_by": ('Nama', 'JK', 'Ayah', 'Ibu', 'Urutan', 'Alamat'),
        "search_by": ('Nama', 'Ayah', 'Ibu', 'Alamat', 'Status Awal', 'Keaktifan'),
        "kolom": {key.title(): value for key, value in DAFTAR_KELAS.items()},
        "show_page": "DK",
        "action": "actionDaftar_Kelas",
        "page_class": PageDaftarKelas,
    },
    "Rekap Siswa": {
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "REKAP_SISWA",
        "action": "actionRekap_Santri",
        "page_class": PageRekapSiswa,
    },
    "Mutasi Masuk": {
        "order_by": ['Nama', 'JK', 'Aktif', 'No Urut'],
        "search_by": ['Nama', 'Ayah', 'Ibu'],
        "kolom": [],
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "MUTASI_MASUK",
        "action": "actionMutasiMasuk",
        "page_class": PageMutasiMasuk,
    },
    "Mutasi Keluar": {
        "order_by": ['Nama', 'JK', 'Tanggal Keluar', 'Tanggal Keluar DESC'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "show_page": "MUTASI_KELUAR",
        "action": "actionMutasiKeluar",
        "page_class": PageMutasiKeluar,
    },
    "Pindah Kelas": {
        "order_by": ['Nama', 'Pilihan Jenjang', 'Alamat', 'JK'],
        "search_by": ['Nama', 'Alamat', 'Ayah', 'Ibu'],
        "kolom": {key.title(): value for key, value in PINDAH_KELAS.items()},
        "hidden_frame": ['kelas'],
        "show_page": "PINDAH_KELAS",
        "action": "actionPindah_Kelas",
        "page_class": PagePindahKelas,
    },
    "MI ke MD": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "hidden_frame": ["jenjang"],
        "show_page": "MI2MD",
        "action": "actionMI_ke_MD",
        "page_class": PageMI2MD,
    },
    "Kenaikan": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "show_page": "NAIK",
        "action": "actionKenaikan",
        "page_class": PageKenaikan,
    },
    "Kelulusan": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama', 'Ayah', 'Ibu', 'NIS'],
        "kolom": [],
        "hidden_frame": ["tingkat", "kelas"],
        "show_page": "LULUS",
        "action": "actionKelulusan",
        "page_class": PageKelulusan,
    },
    "Buku Induk Guru": {
        "order_by": ['Nama', 'JK', 'ID Guru'],
        "search_by": ['Nama'],
        "kolom": [],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "BUKUINDUKGURU",
        "action": "actionBukuIndukGuru",
        "page_class": PageBukuIndukGuru,
    },
    "Keaktifan Guru": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "kolom": {key.title(): value for key, value in GURU.items()},
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "KEAKTIFANGURU",
        "action": "actionRiwayatKeaktifan",
        "page_class": PageKeaktifanGuru,
    },
    "Riwayat Mengajar": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "RIWAYAT_MENGAJAR",
        "action": "actionRiwayat_Mengajar",
        "page_class": PageRiwayatMengajar,
    },
    "Dokumen": {
        "order_by": ['Nama', 'JK'],
        "search_by": ['Nama'],
        "show_page": "DOKUMEN",
        "action": "actionInput_Dokumen",
        "page_class": PageDokumen,
    },
    "Riwayat Kegiatan": {
        "hidden_frame": ['jenjang', 'tingkat', 'kelas'],
        "show_page": "RIWAYAT_KEGIATAN",
        "action": "actionRiwayatKegiatan",
        "page_class": PageRiwayatKegiatan,
    },
    "Peserta": {
        "search_by": ['Nama'],
        "order_by": ['Nama', 'JK'],
        "show_page": "PESERTA",
        "action": "actionPesertaKegiatan",
        "page_class": PagePeserta,
    },
    "Mapel": {
        "show_page": "MAPEL",
        "action": "actionMapelKegiatan",
        "page_class": PageMapel,
    },
    "Input Nilai": {
        "show_page": "INPUT_NILAI",
        "action": "actionInput_Nilai",
        "page_class": PageInputNilai,
    },
    "Rekap Nilai": {
        "show_page": "REKAP_NILAI",
        "action": "actionRekap",
        "page_class": PageRekapNilai,
    },
    "Cetak Rapor": {
        "show_page": "CetakRapor",
        "action": "actionRapor",
        "page_class": PageCetakRapor,
    },
    "Riwayat Kelas": {
        "hidden_frame": ['tingkat', 'kelas'],
        "show_page": "RIWAYAT_KELAS",
        "action": "actionRiwayatKelas",
        "page_class": PageRiwayatKelas,
    },
    "Alamat": {
        "search_by": ['Kampung'],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "ALAMAT",
        "action": "actionAlamat",
        "page_class": PageAlamat,
    },
    "Sekolah": {
        "search_by": ['Nama Sekolah'],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "SEKOLAH",
        "action": "actionSekolah",
        "page_class": PageSekolah,
    },
    "Key Value": {
        "search_by": ['kunci'],
        "hidden_frame": ['jenjang', 'tapel', 'tingkat', 'kelas'],
        "show_page": "KEY_VALUE",
        "action": "actionKey_Value",
        "page_class": PageKeyValue,
    },
    "Biaya": {
        "search_by": ['nama_biaya'],
        "hidden_frame": ['jenjang', 'tingkat', 'kelas'],
        "show_page": "KEY_VALUE",
        "action": "actionBiaya",
        "page_class": PageBiaya,
    },
    "Transaksi Pembayaran": {
        "search_by": ['Nama Lengkap'],
        "hidden_frame": ['jenjang',],
        "show_page": "TRANSAKSI",
        "action": "actionTransaksi_Pembayaran",
        "page_class": PageTransaksi,
    },
    "Riwayat Biaya": {
        "search_by": [],
        "hidden_frame": ['jenjang',],
        "show_page": "RIWAYAT_BIAYA",
        "action": "actionRiwayat_Biaya",
        "page_class": PageRiwayatBiaya,
    },
}