# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QComboBox,
    QFrame, QGridLayout, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QSpacerItem, QTabWidget,
    QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1061, 533)
        self.actionDaftar_Kelas = QAction(MainWindow)
        self.actionDaftar_Kelas.setObjectName(u"actionDaftar_Kelas")
        self.actionDaftar_Kelas.setCheckable(False)
        self.actionDaftar_Kelas.setChecked(False)
        self.actionRekap_Santri = QAction(MainWindow)
        self.actionRekap_Santri.setObjectName(u"actionRekap_Santri")
        self.actionBukuIndukGuru = QAction(MainWindow)
        self.actionBukuIndukGuru.setObjectName(u"actionBukuIndukGuru")
        self.actionPindah_Kelas = QAction(MainWindow)
        self.actionPindah_Kelas.setObjectName(u"actionPindah_Kelas")
        self.actionMutasiKeluar = QAction(MainWindow)
        self.actionMutasiKeluar.setObjectName(u"actionMutasiKeluar")
        self.actionMutasiMasuk = QAction(MainWindow)
        self.actionMutasiMasuk.setObjectName(u"actionMutasiMasuk")
        self.actionKenaikan = QAction(MainWindow)
        self.actionKenaikan.setObjectName(u"actionKenaikan")
        self.actionKelulusan = QAction(MainWindow)
        self.actionKelulusan.setObjectName(u"actionKelulusan")
        self.actionMI_ke_MD = QAction(MainWindow)
        self.actionMI_ke_MD.setObjectName(u"actionMI_ke_MD")
        self.actionBukuInduk = QAction(MainWindow)
        self.actionBukuInduk.setObjectName(u"actionBukuInduk")
        self.actionCari = QAction(MainWindow)
        self.actionCari.setObjectName(u"actionCari")
        self.actionRekap = QAction(MainWindow)
        self.actionRekap.setObjectName(u"actionRekap")
        self.actionRapor = QAction(MainWindow)
        self.actionRapor.setObjectName(u"actionRapor")
        self.actionKartu_Peserta = QAction(MainWindow)
        self.actionKartu_Peserta.setObjectName(u"actionKartu_Peserta")
        self.actionRiwayatKeaktifan = QAction(MainWindow)
        self.actionRiwayatKeaktifan.setObjectName(u"actionRiwayatKeaktifan")
        self.actionAdmGuru = QAction(MainWindow)
        self.actionAdmGuru.setObjectName(u"actionAdmGuru")
        self.actionTabelAll = QAction(MainWindow)
        self.actionTabelAll.setObjectName(u"actionTabelAll")
        self.actionInput_By_Excel = QAction(MainWindow)
        self.actionInput_By_Excel.setObjectName(u"actionInput_By_Excel")
        self.actionShow_Filter = QAction(MainWindow)
        self.actionShow_Filter.setObjectName(u"actionShow_Filter")
        self.actionShow_Filter.setCheckable(True)
        self.actionShow_Filter.setChecked(True)
        self.actionInput_Nilai = QAction(MainWindow)
        self.actionInput_Nilai.setObjectName(u"actionInput_Nilai")
        self.actionRiwayat_Mengajar = QAction(MainWindow)
        self.actionRiwayat_Mengajar.setObjectName(u"actionRiwayat_Mengajar")
        self.actionRiwayatKelas = QAction(MainWindow)
        self.actionRiwayatKelas.setObjectName(u"actionRiwayatKelas")
        self.actionAlamat = QAction(MainWindow)
        self.actionAlamat.setObjectName(u"actionAlamat")
        self.actionSekolah = QAction(MainWindow)
        self.actionSekolah.setObjectName(u"actionSekolah")
        self.actionRiwayatKegiatan = QAction(MainWindow)
        self.actionRiwayatKegiatan.setObjectName(u"actionRiwayatKegiatan")
        self.actionPesertaKegiatan = QAction(MainWindow)
        self.actionPesertaKegiatan.setObjectName(u"actionPesertaKegiatan")
        self.actionMapelKegiatan = QAction(MainWindow)
        self.actionMapelKegiatan.setObjectName(u"actionMapelKegiatan")
        self.actionEkskulKegiatan = QAction(MainWindow)
        self.actionEkskulKegiatan.setObjectName(u"actionEkskulKegiatan")
        self.actionTambah_Dokumen = QAction(MainWindow)
        self.actionTambah_Dokumen.setObjectName(u"actionTambah_Dokumen")
        self.actionHapus_Dokumen = QAction(MainWindow)
        self.actionHapus_Dokumen.setObjectName(u"actionHapus_Dokumen")
        self.actionLihat_Dokumen = QAction(MainWindow)
        self.actionLihat_Dokumen.setObjectName(u"actionLihat_Dokumen")
        self.actionRename_Dokumen = QAction(MainWindow)
        self.actionRename_Dokumen.setObjectName(u"actionRename_Dokumen")
        self.actionGanti_Dokumen = QAction(MainWindow)
        self.actionGanti_Dokumen.setObjectName(u"actionGanti_Dokumen")
        self.actionCompare_Dokumen = QAction(MainWindow)
        self.actionCompare_Dokumen.setObjectName(u"actionCompare_Dokumen")
        self.actionCopy_Dokumen = QAction(MainWindow)
        self.actionCopy_Dokumen.setObjectName(u"actionCopy_Dokumen")
        self.actionApp_Setting = QAction(MainWindow)
        self.actionApp_Setting.setObjectName(u"actionApp_Setting")
        self.actionCeklis_EMIS = QAction(MainWindow)
        self.actionCeklis_EMIS.setObjectName(u"actionCeklis_EMIS")
        self.actionCeklis_VervalPD = QAction(MainWindow)
        self.actionCeklis_VervalPD.setObjectName(u"actionCeklis_VervalPD")
        self.actionExport_Excel = QAction(MainWindow)
        self.actionExport_Excel.setObjectName(u"actionExport_Excel")
        self.actionStatic_Values = QAction(MainWindow)
        self.actionStatic_Values.setObjectName(u"actionStatic_Values")
        self.actionKey_Value = QAction(MainWindow)
        self.actionKey_Value.setObjectName(u"actionKey_Value")
        self.actionDark_Mode = QAction(MainWindow)
        self.actionDark_Mode.setObjectName(u"actionDark_Mode")
        self.actionDark_Mode.setCheckable(True)
        self.actionDark_Mode.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_filter = QFrame(self.centralwidget)
        self.frame_filter.setObjectName(u"frame_filter")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_filter.sizePolicy().hasHeightForWidth())
        self.frame_filter.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(9)
        self.frame_filter.setFont(font)
        self.frame_filter.setFrameShape(QFrame.StyledPanel)
        self.frame_filter.setFrameShadow(QFrame.Raised)
        self.frame_filter.setLineWidth(0)
        self.gridLayout_7 = QGridLayout(self.frame_filter)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setHorizontalSpacing(10)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setContentsMargins(5, 5, 5, 5)
        self.frame_kelas = QWidget(self.frame_filter)
        self.frame_kelas.setObjectName(u"frame_kelas")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_kelas.sizePolicy().hasHeightForWidth())
        self.frame_kelas.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.frame_kelas.setFont(font1)
        self.gridLayout_5 = QGridLayout(self.frame_kelas)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 5, 0)
        self.list_kelas = QListWidget(self.frame_kelas)
        self.list_kelas.setObjectName(u"list_kelas")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.list_kelas.sizePolicy().hasHeightForWidth())
        self.list_kelas.setSizePolicy(sizePolicy2)
        self.list_kelas.setMinimumSize(QSize(0, 28))
        self.list_kelas.setMaximumSize(QSize(300, 28))
        self.list_kelas.setLineWidth(0)
        self.list_kelas.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_kelas.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_kelas.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.list_kelas.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.list_kelas.setFlow(QListView.LeftToRight)
        self.list_kelas.setProperty(u"isWrapping", False)
        self.list_kelas.setResizeMode(QListView.Fixed)
        self.list_kelas.setLayoutMode(QListView.SinglePass)
        self.list_kelas.setSpacing(0)
        self.list_kelas.setViewMode(QListView.ListMode)

        self.gridLayout_5.addWidget(self.list_kelas, 0, 0, 1, 2)


        self.gridLayout_7.addWidget(self.frame_kelas, 0, 8, 1, 1)

        self.frame_tingkat = QWidget(self.frame_filter)
        self.frame_tingkat.setObjectName(u"frame_tingkat")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frame_tingkat.sizePolicy().hasHeightForWidth())
        self.frame_tingkat.setSizePolicy(sizePolicy3)
        self.frame_tingkat.setMinimumSize(QSize(0, 20))
        self.frame_tingkat.setFont(font1)
        self.gridLayout_4 = QGridLayout(self.frame_tingkat)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.list_tingkat = QListWidget(self.frame_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        self.list_tingkat.setObjectName(u"list_tingkat")
        sizePolicy2.setHeightForWidth(self.list_tingkat.sizePolicy().hasHeightForWidth())
        self.list_tingkat.setSizePolicy(sizePolicy2)
        self.list_tingkat.setMinimumSize(QSize(160, 28))
        self.list_tingkat.setMaximumSize(QSize(110, 28))
        font2 = QFont()
        font2.setFamilies([u"Aptos Narrow"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.list_tingkat.setFont(font2)
        self.list_tingkat.setLineWidth(0)
        self.list_tingkat.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_tingkat.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_tingkat.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.list_tingkat.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.list_tingkat.setFlow(QListView.LeftToRight)
        self.list_tingkat.setProperty(u"isWrapping", False)
        self.list_tingkat.setResizeMode(QListView.Fixed)
        self.list_tingkat.setLayoutMode(QListView.Batched)
        self.list_tingkat.setSpacing(0)
        self.list_tingkat.setViewMode(QListView.ListMode)

        self.gridLayout_4.addWidget(self.list_tingkat, 0, 0, 1, 2)


        self.gridLayout_7.addWidget(self.frame_tingkat, 0, 7, 1, 1)

        self.frame_tapel = QWidget(self.frame_filter)
        self.frame_tapel.setObjectName(u"frame_tapel")
        sizePolicy3.setHeightForWidth(self.frame_tapel.sizePolicy().hasHeightForWidth())
        self.frame_tapel.setSizePolicy(sizePolicy3)
        self.frame_tapel.setFont(font1)
        self.frame_tapel.setMouseTracking(True)
        self.frame_tapel.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.frame_tapel.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_3 = QGridLayout(self.frame_tapel)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.cbo_tapel = QComboBox(self.frame_tapel)
        self.cbo_tapel.setObjectName(u"cbo_tapel")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.cbo_tapel.sizePolicy().hasHeightForWidth())
        self.cbo_tapel.setSizePolicy(sizePolicy4)
        self.cbo_tapel.setMinimumSize(QSize(100, 25))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Semibold"])
        font3.setPointSize(9)
        self.cbo_tapel.setFont(font3)
        self.cbo_tapel.setMaxVisibleItems(30)

        self.gridLayout_3.addWidget(self.cbo_tapel, 0, 0, 1, 2)


        self.gridLayout_7.addWidget(self.frame_tapel, 0, 4, 1, 1)

        self.frame_search = QWidget(self.frame_filter)
        self.frame_search.setObjectName(u"frame_search")
        sizePolicy3.setHeightForWidth(self.frame_search.sizePolicy().hasHeightForWidth())
        self.frame_search.setSizePolicy(sizePolicy3)
        self.frame_search.setMinimumSize(QSize(100, 0))
        self.frame_search.setFont(font1)
        self.frame_search.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_6 = QGridLayout(self.frame_search)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setHorizontalSpacing(5)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.line_search = QLineEdit(self.frame_search)
        self.line_search.setObjectName(u"line_search")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.line_search.sizePolicy().hasHeightForWidth())
        self.line_search.setSizePolicy(sizePolicy5)
        self.line_search.setMinimumSize(QSize(120, 28))
        self.line_search.setMaximumSize(QSize(120, 16777215))
        self.line_search.setFont(font)
        self.line_search.setFrame(True)
        self.line_search.setClearButtonEnabled(True)

        self.gridLayout_6.addWidget(self.line_search, 0, 0, 1, 2)

        self.cbo_search_by = QComboBox(self.frame_search)
        self.cbo_search_by.setObjectName(u"cbo_search_by")
        self.cbo_search_by.setMinimumSize(QSize(100, 28))
        self.cbo_search_by.setMaximumSize(QSize(120, 16777215))
        self.cbo_search_by.setFont(font)
        self.cbo_search_by.setEditable(False)
        self.cbo_search_by.setFrame(False)

        self.gridLayout_6.addWidget(self.cbo_search_by, 0, 2, 1, 1)


        self.gridLayout_7.addWidget(self.frame_search, 0, 14, 1, 1)

        self.frame_jenjang = QWidget(self.frame_filter)
        self.frame_jenjang.setObjectName(u"frame_jenjang")
        sizePolicy1.setHeightForWidth(self.frame_jenjang.sizePolicy().hasHeightForWidth())
        self.frame_jenjang.setSizePolicy(sizePolicy1)
        self.frame_jenjang.setMaximumSize(QSize(80, 16777215))
        self.frame_jenjang.setFont(font1)
        self.frame_jenjang.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_2 = QGridLayout(self.frame_jenjang)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.list_jenjang = QListWidget(self.frame_jenjang)
        QListWidgetItem(self.list_jenjang)
        QListWidgetItem(self.list_jenjang)
        self.list_jenjang.setObjectName(u"list_jenjang")
        sizePolicy2.setHeightForWidth(self.list_jenjang.sizePolicy().hasHeightForWidth())
        self.list_jenjang.setSizePolicy(sizePolicy2)
        self.list_jenjang.setMinimumSize(QSize(60, 28))
        self.list_jenjang.setMaximumSize(QSize(16777215, 28))
        self.list_jenjang.setFont(font2)
        self.list_jenjang.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_jenjang.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_jenjang.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.list_jenjang.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.list_jenjang.setFlow(QListView.LeftToRight)
        self.list_jenjang.setViewMode(QListView.ListMode)

        self.gridLayout_2.addWidget(self.list_jenjang, 0, 0, 1, 2)


        self.gridLayout_7.addWidget(self.frame_jenjang, 0, 1, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_7.addItem(self.horizontalSpacer_2, 0, 13, 1, 1)

        self.frame_order_by = QWidget(self.frame_filter)
        self.frame_order_by.setObjectName(u"frame_order_by")
        sizePolicy1.setHeightForWidth(self.frame_order_by.sizePolicy().hasHeightForWidth())
        self.frame_order_by.setSizePolicy(sizePolicy1)
        self.frame_order_by.setFont(font1)
        self.gridLayout_8 = QGridLayout(self.frame_order_by)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.cbo_order_by = QComboBox(self.frame_order_by)
        self.cbo_order_by.setObjectName(u"cbo_order_by")
        sizePolicy5.setHeightForWidth(self.cbo_order_by.sizePolicy().hasHeightForWidth())
        self.cbo_order_by.setSizePolicy(sizePolicy5)
        self.cbo_order_by.setMinimumSize(QSize(100, 25))
        self.cbo_order_by.setFont(font3)

        self.gridLayout_8.addWidget(self.cbo_order_by, 0, 0, 1, 2)


        self.gridLayout_7.addWidget(self.frame_order_by, 0, 5, 1, 1)

        self.frame_kolom = QWidget(self.frame_filter)
        self.frame_kolom.setObjectName(u"frame_kolom")
        sizePolicy1.setHeightForWidth(self.frame_kolom.sizePolicy().hasHeightForWidth())
        self.frame_kolom.setSizePolicy(sizePolicy1)
        self.frame_kolom.setFont(font1)
        self.gridLayout_9 = QGridLayout(self.frame_kolom)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.cbo_kolom = QComboBox(self.frame_kolom)
        self.cbo_kolom.setObjectName(u"cbo_kolom")
        sizePolicy5.setHeightForWidth(self.cbo_kolom.sizePolicy().hasHeightForWidth())
        self.cbo_kolom.setSizePolicy(sizePolicy5)
        self.cbo_kolom.setMinimumSize(QSize(120, 25))
        self.cbo_kolom.setFont(font3)
        self.cbo_kolom.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.gridLayout_9.addWidget(self.cbo_kolom, 0, 0, 1, 2)


        self.gridLayout_7.addWidget(self.frame_kolom, 0, 6, 1, 1)


        self.gridLayout.addWidget(self.frame_filter, 0, 0, 1, 1)

        self.main_tab = QTabWidget(self.centralwidget)
        self.main_tab.setObjectName(u"main_tab")
        self.main_tab.setFont(font)
        self.main_tab.setAutoFillBackground(True)
        self.main_tab.setTabShape(QTabWidget.Rounded)
        self.main_tab.setIconSize(QSize(10, 10))
        self.main_tab.setDocumentMode(False)
        self.main_tab.setTabsClosable(True)
        self.main_tab.setTabBarAutoHide(False)

        self.gridLayout.addWidget(self.main_tab, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1061, 21))
        self.menuSantri = QMenu(self.menuBar)
        self.menuSantri.setObjectName(u"menuSantri")
        self.menuGuru = QMenu(self.menuBar)
        self.menuGuru.setObjectName(u"menuGuru")
        self.menuSetting = QMenu(self.menuBar)
        self.menuSetting.setObjectName(u"menuSetting")
        self.menuSetting.setTearOffEnabled(False)
        self.menuNilai = QMenu(self.menuBar)
        self.menuNilai.setObjectName(u"menuNilai")
        self.menuPengaturan = QMenu(self.menuNilai)
        self.menuPengaturan.setObjectName(u"menuPengaturan")
        self.menuCetak = QMenu(self.menuNilai)
        self.menuCetak.setObjectName(u"menuCetak")
        self.menuDokumen = QMenu(self.menuBar)
        self.menuDokumen.setObjectName(u"menuDokumen")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuPreferensi_2 = QMenu(self.menuBar)
        self.menuPreferensi_2.setObjectName(u"menuPreferensi_2")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuSantri.menuAction())
        self.menuBar.addAction(self.menuGuru.menuAction())
        self.menuBar.addAction(self.menuNilai.menuAction())
        self.menuBar.addAction(self.menuDokumen.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menuPreferensi_2.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuSantri.addAction(self.actionDaftar_Kelas)
        self.menuSantri.addAction(self.actionRekap_Santri)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionMutasiMasuk)
        self.menuSantri.addAction(self.actionMutasiKeluar)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionPindah_Kelas)
        self.menuSantri.addAction(self.actionMI_ke_MD)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionKenaikan)
        self.menuSantri.addAction(self.actionKelulusan)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionCari)
        self.menuSantri.addAction(self.actionBukuInduk)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionCeklis_EMIS)
        self.menuGuru.addAction(self.actionBukuIndukGuru)
        self.menuGuru.addAction(self.actionRiwayatKeaktifan)
        self.menuGuru.addAction(self.actionRiwayat_Mengajar)
        self.menuGuru.addAction(self.actionAdmGuru)
        self.menuSetting.addAction(self.actionInput_By_Excel)
        self.menuSetting.addAction(self.actionExport_Excel)
        self.menuSetting.addAction(self.actionApp_Setting)
        self.menuNilai.addAction(self.menuPengaturan.menuAction())
        self.menuNilai.addSeparator()
        self.menuNilai.addAction(self.actionInput_Nilai)
        self.menuNilai.addSeparator()
        self.menuNilai.addAction(self.menuCetak.menuAction())
        self.menuPengaturan.addAction(self.actionRiwayatKegiatan)
        self.menuPengaturan.addAction(self.actionPesertaKegiatan)
        self.menuPengaturan.addAction(self.actionMapelKegiatan)
        self.menuPengaturan.addAction(self.actionEkskulKegiatan)
        self.menuCetak.addAction(self.actionKartu_Peserta)
        self.menuCetak.addAction(self.actionRekap)
        self.menuCetak.addAction(self.actionRapor)
        self.menuDokumen.addAction(self.actionLihat_Dokumen)
        self.menuDokumen.addAction(self.actionTambah_Dokumen)
        self.menuDokumen.addAction(self.actionCopy_Dokumen)
        self.menuDokumen.addAction(self.actionCompare_Dokumen)
        self.menuDokumen.addAction(self.actionRename_Dokumen)
        self.menuDokumen.addAction(self.actionGanti_Dokumen)
        self.menuDokumen.addAction(self.actionHapus_Dokumen)
        self.menuView.addAction(self.actionShow_Filter)
        self.menuView.addAction(self.actionDark_Mode)
        self.menuPreferensi_2.addAction(self.actionRiwayatKelas)
        self.menuPreferensi_2.addAction(self.actionAlamat)
        self.menuPreferensi_2.addAction(self.actionSekolah)
        self.menuPreferensi_2.addAction(self.actionKey_Value)
        self.menuPreferensi_2.addAction(self.actionStatic_Values)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDaftar_Kelas.setText(QCoreApplication.translate("MainWindow", u"Daftar Kelas", None))
#if QT_CONFIG(shortcut)
        self.actionDaftar_Kelas.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionRekap_Santri.setText(QCoreApplication.translate("MainWindow", u"Rekap Santri", None))
#if QT_CONFIG(shortcut)
        self.actionRekap_Santri.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionBukuIndukGuru.setText(QCoreApplication.translate("MainWindow", u"Buku Induk Guru", None))
        self.actionPindah_Kelas.setText(QCoreApplication.translate("MainWindow", u"Pindah Kelas", None))
        self.actionMutasiKeluar.setText(QCoreApplication.translate("MainWindow", u"Keluar", None))
        self.actionMutasiMasuk.setText(QCoreApplication.translate("MainWindow", u"Masuk", None))
        self.actionKenaikan.setText(QCoreApplication.translate("MainWindow", u"Kenaikan", None))
        self.actionKelulusan.setText(QCoreApplication.translate("MainWindow", u"Kelulusan", None))
        self.actionMI_ke_MD.setText(QCoreApplication.translate("MainWindow", u"MI ke MD", None))
        self.actionBukuInduk.setText(QCoreApplication.translate("MainWindow", u"Buku Induk", None))
        self.actionCari.setText(QCoreApplication.translate("MainWindow", u"Cari", None))
        self.actionRekap.setText(QCoreApplication.translate("MainWindow", u"Cetak Rekap", None))
        self.actionRapor.setText(QCoreApplication.translate("MainWindow", u"Cetak Rapor", None))
        self.actionKartu_Peserta.setText(QCoreApplication.translate("MainWindow", u"Cetak Kartu Peserta", None))
        self.actionRiwayatKeaktifan.setText(QCoreApplication.translate("MainWindow", u"Riwayat Keaktifan", None))
        self.actionAdmGuru.setText(QCoreApplication.translate("MainWindow", u"Adm Guru", None))
        self.actionTabelAll.setText(QCoreApplication.translate("MainWindow", u"Tabel", None))
        self.actionInput_By_Excel.setText(QCoreApplication.translate("MainWindow", u"Input By Excel", None))
        self.actionShow_Filter.setText(QCoreApplication.translate("MainWindow", u"Show Filter", None))
        self.actionInput_Nilai.setText(QCoreApplication.translate("MainWindow", u"Input Nilai", None))
        self.actionRiwayat_Mengajar.setText(QCoreApplication.translate("MainWindow", u"Riwayat Mengajar", None))
        self.actionRiwayatKelas.setText(QCoreApplication.translate("MainWindow", u"Riwayat Kelas", None))
        self.actionAlamat.setText(QCoreApplication.translate("MainWindow", u"Alamat", None))
        self.actionSekolah.setText(QCoreApplication.translate("MainWindow", u"Sekolah", None))
        self.actionRiwayatKegiatan.setText(QCoreApplication.translate("MainWindow", u"Riwayat Kegiatan", None))
        self.actionPesertaKegiatan.setText(QCoreApplication.translate("MainWindow", u"Peserta", None))
        self.actionMapelKegiatan.setText(QCoreApplication.translate("MainWindow", u"Mapel Kegiatan", None))
        self.actionEkskulKegiatan.setText(QCoreApplication.translate("MainWindow", u"Ekskul Kegiatan", None))
        self.actionTambah_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Tambah Dokumen", None))
        self.actionHapus_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Hapus Dokumen", None))
        self.actionLihat_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Lihat Dokumen", None))
        self.actionRename_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Rename Dokumen", None))
        self.actionGanti_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Ganti Dokumen", None))
        self.actionCompare_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Bandingkan Dokumen", None))
        self.actionCopy_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Copy Dokumen", None))
        self.actionApp_Setting.setText(QCoreApplication.translate("MainWindow", u"App Setting", None))
        self.actionCeklis_EMIS.setText(QCoreApplication.translate("MainWindow", u"Ceklis EMIS", None))
        self.actionCeklis_VervalPD.setText(QCoreApplication.translate("MainWindow", u"Ceklis VervalPD", None))
        self.actionExport_Excel.setText(QCoreApplication.translate("MainWindow", u"Export Excel", None))
        self.actionStatic_Values.setText(QCoreApplication.translate("MainWindow", u"Static Values", None))
        self.actionKey_Value.setText(QCoreApplication.translate("MainWindow", u"Key Value", None))
        self.actionDark_Mode.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))

        __sortingEnabled = self.list_tingkat.isSortingEnabled()
        self.list_tingkat.setSortingEnabled(False)
        ___qlistwidgetitem = self.list_tingkat.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u" 1 ", None));
        ___qlistwidgetitem1 = self.list_tingkat.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u" 2 ", None));
        ___qlistwidgetitem2 = self.list_tingkat.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u" 3 ", None));
        ___qlistwidgetitem3 = self.list_tingkat.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u" 4 ", None));
        ___qlistwidgetitem4 = self.list_tingkat.item(4)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u" 5 ", None));
        ___qlistwidgetitem5 = self.list_tingkat.item(5)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("MainWindow", u" 6 ", None));
        self.list_tingkat.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.list_jenjang.isSortingEnabled()
        self.list_jenjang.setSortingEnabled(False)
        ___qlistwidgetitem6 = self.list_jenjang.item(0)
        ___qlistwidgetitem6.setText(QCoreApplication.translate("MainWindow", u"  MI  ", None));
        ___qlistwidgetitem7 = self.list_jenjang.item(1)
        ___qlistwidgetitem7.setText(QCoreApplication.translate("MainWindow", u"  MD  ", None));
        self.list_jenjang.setSortingEnabled(__sortingEnabled1)

        self.menuSantri.setTitle(QCoreApplication.translate("MainWindow", u"Santri", None))
        self.menuGuru.setTitle(QCoreApplication.translate("MainWindow", u"Guru", None))
        self.menuSetting.setTitle(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.menuNilai.setTitle(QCoreApplication.translate("MainWindow", u"Nilai", None))
        self.menuPengaturan.setTitle(QCoreApplication.translate("MainWindow", u"Pengaturan", None))
        self.menuCetak.setTitle(QCoreApplication.translate("MainWindow", u"Cetak", None))
        self.menuDokumen.setTitle(QCoreApplication.translate("MainWindow", u"Dokumen", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuPreferensi_2.setTitle(QCoreApplication.translate("MainWindow", u"Preferensi", None))
    # retranslateUi

