# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSpacerItem,
    QTabWidget, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1117, 1424)
        self.actionDaftar_Kelas = QAction(MainWindow)
        self.actionDaftar_Kelas.setObjectName(u"actionDaftar_Kelas")
        self.actionDaftar_Kelas.setCheckable(False)
        self.actionDaftar_Kelas.setChecked(False)
        self.actionRekap_Santri = QAction(MainWindow)
        self.actionRekap_Santri.setObjectName(u"actionRekap_Santri")
        self.actionBukuIndukGuru = QAction(MainWindow)
        self.actionBukuIndukGuru.setObjectName(u"actionBukuIndukGuru")
        self.actionPindah_Kelas = QAction(MainWindow)
        self.actionPindah_Kelas.setObjectName(u"actionPindah_Kelas")
        self.actionMutasiKeluar = QAction(MainWindow)
        self.actionMutasiKeluar.setObjectName(u"actionMutasiKeluar")
        self.actionMutasiMasuk = QAction(MainWindow)
        self.actionMutasiMasuk.setObjectName(u"actionMutasiMasuk")
        self.actionKenaikan = QAction(MainWindow)
        self.actionKenaikan.setObjectName(u"actionKenaikan")
        self.actionKelulusan = QAction(MainWindow)
        self.actionKelulusan.setObjectName(u"actionKelulusan")
        self.actionMI_ke_MD = QAction(MainWindow)
        self.actionMI_ke_MD.setObjectName(u"actionMI_ke_MD")
        self.actionTabel = QAction(MainWindow)
        self.actionTabel.setObjectName(u"actionTabel")
        self.actionCari = QAction(MainWindow)
        self.actionCari.setObjectName(u"actionCari")
        self.actionRekap = QAction(MainWindow)
        self.actionRekap.setObjectName(u"actionRekap")
        self.actionRapor = QAction(MainWindow)
        self.actionRapor.setObjectName(u"actionRapor")
        self.actionKartu_Peserta = QAction(MainWindow)
        self.actionKartu_Peserta.setObjectName(u"actionKartu_Peserta")
        self.actionLabel_Sampul = QAction(MainWindow)
        self.actionLabel_Sampul.setObjectName(u"actionLabel_Sampul")
        self.actionRiwayatKeaktifan = QAction(MainWindow)
        self.actionRiwayatKeaktifan.setObjectName(u"actionRiwayatKeaktifan")
        self.actionAdmGuru = QAction(MainWindow)
        self.actionAdmGuru.setObjectName(u"actionAdmGuru")
        self.actionTabelAll = QAction(MainWindow)
        self.actionTabelAll.setObjectName(u"actionTabelAll")
        self.actionInput_Dokumen = QAction(MainWindow)
        self.actionInput_Dokumen.setObjectName(u"actionInput_Dokumen")
        self.actionInput_By_Excel = QAction(MainWindow)
        self.actionInput_By_Excel.setObjectName(u"actionInput_By_Excel")
        self.actionShow_Filter = QAction(MainWindow)
        self.actionShow_Filter.setObjectName(u"actionShow_Filter")
        self.actionShow_Filter.setCheckable(True)
        self.actionShow_Filter.setChecked(True)
        self.actionInput_Riwayat = QAction(MainWindow)
        self.actionInput_Riwayat.setObjectName(u"actionInput_Riwayat")
        self.actionClear_hashdata = QAction(MainWindow)
        self.actionClear_hashdata.setObjectName(u"actionClear_hashdata")
        self.actionInput_Nilai = QAction(MainWindow)
        self.actionInput_Nilai.setObjectName(u"actionInput_Nilai")
        self.actionRiwayat_Mengajar = QAction(MainWindow)
        self.actionRiwayat_Mengajar.setObjectName(u"actionRiwayat_Mengajar")
        self.actionRiwayatKelas = QAction(MainWindow)
        self.actionRiwayatKelas.setObjectName(u"actionRiwayatKelas")
        self.actionAlamat = QAction(MainWindow)
        self.actionAlamat.setObjectName(u"actionAlamat")
        self.actionSekolah = QAction(MainWindow)
        self.actionSekolah.setObjectName(u"actionSekolah")
        self.actionKey_Value = QAction(MainWindow)
        self.actionKey_Value.setObjectName(u"actionKey_Value")
        self.actionRiwayatKegiatan = QAction(MainWindow)
        self.actionRiwayatKegiatan.setObjectName(u"actionRiwayatKegiatan")
        self.actionPesertaKegiatan = QAction(MainWindow)
        self.actionPesertaKegiatan.setObjectName(u"actionPesertaKegiatan")
        self.actionMapelKegiatan = QAction(MainWindow)
        self.actionMapelKegiatan.setObjectName(u"actionMapelKegiatan")
        self.actionEkskulKegiatan = QAction(MainWindow)
        self.actionEkskulKegiatan.setObjectName(u"actionEkskulKegiatan")
        self.actionTransaksi_Pembayaran = QAction(MainWindow)
        self.actionTransaksi_Pembayaran.setObjectName(u"actionTransaksi_Pembayaran")
        self.actionBiaya = QAction(MainWindow)
        self.actionBiaya.setObjectName(u"actionBiaya")
        self.actionDispensasi = QAction(MainWindow)
        self.actionDispensasi.setObjectName(u"actionDispensasi")
        self.actionRiwayat_Biaya = QAction(MainWindow)
        self.actionRiwayat_Biaya.setObjectName(u"actionRiwayat_Biaya")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_filter = QFrame(self.centralwidget)
        self.frame_filter.setObjectName(u"frame_filter")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_filter.sizePolicy().hasHeightForWidth())
        self.frame_filter.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(9)
        self.frame_filter.setFont(font)
        self.frame_filter.setFrameShape(QFrame.StyledPanel)
        self.frame_filter.setFrameShadow(QFrame.Raised)
        self.gridLayout_7 = QGridLayout(self.frame_filter)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setHorizontalSpacing(10)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setContentsMargins(5, 5, 5, 5)
        self.frame_order_by = QWidget(self.frame_filter)
        self.frame_order_by.setObjectName(u"frame_order_by")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_order_by.sizePolicy().hasHeightForWidth())
        self.frame_order_by.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.frame_order_by.setFont(font1)
        self.gridLayout_8 = QGridLayout(self.frame_order_by)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.prev_order_by = QPushButton(self.frame_order_by)
        self.prev_order_by.setObjectName(u"prev_order_by")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.prev_order_by.sizePolicy().hasHeightForWidth())
        self.prev_order_by.setSizePolicy(sizePolicy2)
        self.prev_order_by.setMinimumSize(QSize(20, 24))
        self.prev_order_by.setMaximumSize(QSize(20, 24))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI"])
        font2.setPointSize(9)
        font2.setBold(False)
        self.prev_order_by.setFont(font2)
        self.prev_order_by.setIconSize(QSize(10, 10))
        self.prev_order_by.setFlat(False)

        self.gridLayout_8.addWidget(self.prev_order_by, 0, 0, 1, 1)

        self.label_order = QLabel(self.frame_order_by)
        self.label_order.setObjectName(u"label_order")
        self.label_order.setMinimumSize(QSize(0, 0))
        self.label_order.setMaximumSize(QSize(16777215, 20))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setItalic(False)
        self.label_order.setFont(font3)
        self.label_order.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.label_order, 0, 1, 1, 1)

        self.next_order_by = QPushButton(self.frame_order_by)
        self.next_order_by.setObjectName(u"next_order_by")
        sizePolicy2.setHeightForWidth(self.next_order_by.sizePolicy().hasHeightForWidth())
        self.next_order_by.setSizePolicy(sizePolicy2)
        self.next_order_by.setMinimumSize(QSize(20, 24))
        self.next_order_by.setMaximumSize(QSize(20, 24))
        self.next_order_by.setFont(font2)
        self.next_order_by.setIconSize(QSize(10, 10))
        self.next_order_by.setFlat(False)

        self.gridLayout_8.addWidget(self.next_order_by, 0, 2, 1, 1)

        self.cbo_order_by = QComboBox(self.frame_order_by)
        self.cbo_order_by.setObjectName(u"cbo_order_by")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.cbo_order_by.sizePolicy().hasHeightForWidth())
        self.cbo_order_by.setSizePolicy(sizePolicy3)
        self.cbo_order_by.setMinimumSize(QSize(120, 25))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Semibold"])
        font4.setPointSize(9)
        self.cbo_order_by.setFont(font4)

        self.gridLayout_8.addWidget(self.cbo_order_by, 1, 0, 1, 3)


        self.gridLayout_7.addWidget(self.frame_order_by, 0, 7, 1, 1)

        self.frame_tapel = QWidget(self.frame_filter)
        self.frame_tapel.setObjectName(u"frame_tapel")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frame_tapel.sizePolicy().hasHeightForWidth())
        self.frame_tapel.setSizePolicy(sizePolicy4)
        self.frame_tapel.setFont(font1)
        self.frame_tapel.setMouseTracking(True)
        self.frame_tapel.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.frame_tapel.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_3 = QGridLayout(self.frame_tapel)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.cbo_tapel = QComboBox(self.frame_tapel)
        self.cbo_tapel.setObjectName(u"cbo_tapel")
        sizePolicy2.setHeightForWidth(self.cbo_tapel.sizePolicy().hasHeightForWidth())
        self.cbo_tapel.setSizePolicy(sizePolicy2)
        self.cbo_tapel.setMinimumSize(QSize(100, 25))
        self.cbo_tapel.setFont(font4)
        self.cbo_tapel.setMaxVisibleItems(20)

        self.gridLayout_3.addWidget(self.cbo_tapel, 1, 0, 1, 3)

        self.prev_tapel = QPushButton(self.frame_tapel)
        self.prev_tapel.setObjectName(u"prev_tapel")
        sizePolicy2.setHeightForWidth(self.prev_tapel.sizePolicy().hasHeightForWidth())
        self.prev_tapel.setSizePolicy(sizePolicy2)
        self.prev_tapel.setMinimumSize(QSize(20, 24))
        self.prev_tapel.setMaximumSize(QSize(20, 24))
        font5 = QFont()
        font5.setFamilies([u"Segoe UI"])
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setItalic(False)
        self.prev_tapel.setFont(font5)
        self.prev_tapel.setIconSize(QSize(10, 10))
        self.prev_tapel.setFlat(False)

        self.gridLayout_3.addWidget(self.prev_tapel, 0, 0, 1, 1)

        self.next_tapel = QPushButton(self.frame_tapel)
        self.next_tapel.setObjectName(u"next_tapel")
        sizePolicy2.setHeightForWidth(self.next_tapel.sizePolicy().hasHeightForWidth())
        self.next_tapel.setSizePolicy(sizePolicy2)
        self.next_tapel.setMinimumSize(QSize(20, 24))
        self.next_tapel.setMaximumSize(QSize(20, 24))
        self.next_tapel.setFont(font5)
        self.next_tapel.setIconSize(QSize(10, 10))
        self.next_tapel.setFlat(False)

        self.gridLayout_3.addWidget(self.next_tapel, 0, 2, 1, 1)

        self.label_tapel = QPushButton(self.frame_tapel)
        self.label_tapel.setObjectName(u"label_tapel")
        self.label_tapel.setFont(font)

        self.gridLayout_3.addWidget(self.label_tapel, 0, 1, 1, 1)


        self.gridLayout_7.addWidget(self.frame_tapel, 0, 4, 1, 1)

        self.frame_jenjang = QWidget(self.frame_filter)
        self.frame_jenjang.setObjectName(u"frame_jenjang")
        sizePolicy4.setHeightForWidth(self.frame_jenjang.sizePolicy().hasHeightForWidth())
        self.frame_jenjang.setSizePolicy(sizePolicy4)
        self.frame_jenjang.setFont(font1)
        self.frame_jenjang.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_2 = QGridLayout(self.frame_jenjang)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.prev_jenjang = QPushButton(self.frame_jenjang)
        self.prev_jenjang.setObjectName(u"prev_jenjang")
        sizePolicy2.setHeightForWidth(self.prev_jenjang.sizePolicy().hasHeightForWidth())
        self.prev_jenjang.setSizePolicy(sizePolicy2)
        self.prev_jenjang.setMinimumSize(QSize(20, 24))
        self.prev_jenjang.setMaximumSize(QSize(20, 24))
        self.prev_jenjang.setFont(font2)
        self.prev_jenjang.setIconSize(QSize(16, 16))

        self.gridLayout_2.addWidget(self.prev_jenjang, 0, 0, 1, 1)

        self.next_jenjang = QPushButton(self.frame_jenjang)
        self.next_jenjang.setObjectName(u"next_jenjang")
        sizePolicy2.setHeightForWidth(self.next_jenjang.sizePolicy().hasHeightForWidth())
        self.next_jenjang.setSizePolicy(sizePolicy2)
        self.next_jenjang.setMinimumSize(QSize(20, 24))
        self.next_jenjang.setMaximumSize(QSize(20, 24))
        self.next_jenjang.setFont(font2)
        self.next_jenjang.setIconSize(QSize(16, 16))
        self.next_jenjang.setFlat(False)

        self.gridLayout_2.addWidget(self.next_jenjang, 0, 2, 1, 1)

        self.cbo_jenjang = QComboBox(self.frame_jenjang)
        self.cbo_jenjang.setObjectName(u"cbo_jenjang")
        self.cbo_jenjang.setMinimumSize(QSize(0, 25))
        self.cbo_jenjang.setFont(font4)

        self.gridLayout_2.addWidget(self.cbo_jenjang, 1, 0, 1, 3)

        self.label_jenjang = QPushButton(self.frame_jenjang)
        self.label_jenjang.setObjectName(u"label_jenjang")
        self.label_jenjang.setFont(font)

        self.gridLayout_2.addWidget(self.label_jenjang, 0, 1, 1, 1)


        self.gridLayout_7.addWidget(self.frame_jenjang, 0, 1, 1, 1)

        self.frame_tingkat = QWidget(self.frame_filter)
        self.frame_tingkat.setObjectName(u"frame_tingkat")
        sizePolicy4.setHeightForWidth(self.frame_tingkat.sizePolicy().hasHeightForWidth())
        self.frame_tingkat.setSizePolicy(sizePolicy4)
        self.frame_tingkat.setMinimumSize(QSize(0, 20))
        self.frame_tingkat.setFont(font1)
        self.gridLayout_4 = QGridLayout(self.frame_tingkat)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.prev_tingkat = QPushButton(self.frame_tingkat)
        self.prev_tingkat.setObjectName(u"prev_tingkat")
        sizePolicy2.setHeightForWidth(self.prev_tingkat.sizePolicy().hasHeightForWidth())
        self.prev_tingkat.setSizePolicy(sizePolicy2)
        self.prev_tingkat.setMinimumSize(QSize(20, 24))
        self.prev_tingkat.setMaximumSize(QSize(20, 24))
        self.prev_tingkat.setFont(font2)
        self.prev_tingkat.setIconSize(QSize(10, 10))
        self.prev_tingkat.setFlat(False)

        self.gridLayout_4.addWidget(self.prev_tingkat, 0, 0, 1, 1)

        self.next_tingkat = QPushButton(self.frame_tingkat)
        self.next_tingkat.setObjectName(u"next_tingkat")
        sizePolicy2.setHeightForWidth(self.next_tingkat.sizePolicy().hasHeightForWidth())
        self.next_tingkat.setSizePolicy(sizePolicy2)
        self.next_tingkat.setMinimumSize(QSize(20, 24))
        self.next_tingkat.setMaximumSize(QSize(20, 24))
        self.next_tingkat.setFont(font2)
        self.next_tingkat.setIconSize(QSize(10, 10))
        self.next_tingkat.setFlat(False)

        self.gridLayout_4.addWidget(self.next_tingkat, 0, 2, 1, 1)

        self.cbo_tingkat = QComboBox(self.frame_tingkat)
        self.cbo_tingkat.setObjectName(u"cbo_tingkat")
        sizePolicy3.setHeightForWidth(self.cbo_tingkat.sizePolicy().hasHeightForWidth())
        self.cbo_tingkat.setSizePolicy(sizePolicy3)
        self.cbo_tingkat.setMinimumSize(QSize(0, 25))
        self.cbo_tingkat.setFont(font4)

        self.gridLayout_4.addWidget(self.cbo_tingkat, 1, 0, 1, 3)

        self.label_tingkat = QPushButton(self.frame_tingkat)
        self.label_tingkat.setObjectName(u"label_tingkat")
        self.label_tingkat.setFont(font)

        self.gridLayout_4.addWidget(self.label_tingkat, 0, 1, 1, 1)


        self.gridLayout_7.addWidget(self.frame_tingkat, 0, 5, 1, 1)

        self.frame_kolom = QWidget(self.frame_filter)
        self.frame_kolom.setObjectName(u"frame_kolom")
        sizePolicy1.setHeightForWidth(self.frame_kolom.sizePolicy().hasHeightForWidth())
        self.frame_kolom.setSizePolicy(sizePolicy1)
        self.frame_kolom.setFont(font1)
        self.gridLayout_9 = QGridLayout(self.frame_kolom)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.prev_kolom = QPushButton(self.frame_kolom)
        self.prev_kolom.setObjectName(u"prev_kolom")
        sizePolicy2.setHeightForWidth(self.prev_kolom.sizePolicy().hasHeightForWidth())
        self.prev_kolom.setSizePolicy(sizePolicy2)
        self.prev_kolom.setMinimumSize(QSize(20, 24))
        self.prev_kolom.setMaximumSize(QSize(20, 24))
        self.prev_kolom.setFont(font2)
        self.prev_kolom.setIconSize(QSize(10, 10))
        self.prev_kolom.setFlat(False)

        self.gridLayout_9.addWidget(self.prev_kolom, 0, 0, 1, 1)

        self.label_kolom = QLabel(self.frame_kolom)
        self.label_kolom.setObjectName(u"label_kolom")
        self.label_kolom.setMinimumSize(QSize(0, 20))
        self.label_kolom.setMaximumSize(QSize(16777215, 20))
        self.label_kolom.setFont(font3)
        self.label_kolom.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.label_kolom, 0, 1, 1, 1)

        self.next_kolom = QPushButton(self.frame_kolom)
        self.next_kolom.setObjectName(u"next_kolom")
        sizePolicy2.setHeightForWidth(self.next_kolom.sizePolicy().hasHeightForWidth())
        self.next_kolom.setSizePolicy(sizePolicy2)
        self.next_kolom.setMinimumSize(QSize(20, 24))
        self.next_kolom.setMaximumSize(QSize(20, 24))
        self.next_kolom.setFont(font2)
        self.next_kolom.setIconSize(QSize(10, 10))
        self.next_kolom.setFlat(False)

        self.gridLayout_9.addWidget(self.next_kolom, 0, 2, 1, 1)

        self.cbo_kolom = QComboBox(self.frame_kolom)
        self.cbo_kolom.setObjectName(u"cbo_kolom")
        sizePolicy3.setHeightForWidth(self.cbo_kolom.sizePolicy().hasHeightForWidth())
        self.cbo_kolom.setSizePolicy(sizePolicy3)
        self.cbo_kolom.setMinimumSize(QSize(150, 25))
        self.cbo_kolom.setFont(font4)
        self.cbo_kolom.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.gridLayout_9.addWidget(self.cbo_kolom, 1, 0, 1, 3)


        self.gridLayout_7.addWidget(self.frame_kolom, 0, 9, 1, 1)

        self.frame_kelas = QWidget(self.frame_filter)
        self.frame_kelas.setObjectName(u"frame_kelas")
        sizePolicy1.setHeightForWidth(self.frame_kelas.sizePolicy().hasHeightForWidth())
        self.frame_kelas.setSizePolicy(sizePolicy1)
        self.frame_kelas.setFont(font1)
        self.gridLayout_5 = QGridLayout(self.frame_kelas)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.next_kelas = QPushButton(self.frame_kelas)
        self.next_kelas.setObjectName(u"next_kelas")
        sizePolicy2.setHeightForWidth(self.next_kelas.sizePolicy().hasHeightForWidth())
        self.next_kelas.setSizePolicy(sizePolicy2)
        self.next_kelas.setMinimumSize(QSize(20, 24))
        self.next_kelas.setMaximumSize(QSize(20, 24))
        self.next_kelas.setFont(font2)
        self.next_kelas.setIconSize(QSize(10, 10))
        self.next_kelas.setFlat(False)

        self.gridLayout_5.addWidget(self.next_kelas, 0, 2, 1, 1)

        self.prev_kelas = QPushButton(self.frame_kelas)
        self.prev_kelas.setObjectName(u"prev_kelas")
        sizePolicy2.setHeightForWidth(self.prev_kelas.sizePolicy().hasHeightForWidth())
        self.prev_kelas.setSizePolicy(sizePolicy2)
        self.prev_kelas.setMinimumSize(QSize(20, 24))
        self.prev_kelas.setMaximumSize(QSize(20, 24))
        self.prev_kelas.setFont(font2)
        self.prev_kelas.setIconSize(QSize(10, 10))
        self.prev_kelas.setFlat(False)

        self.gridLayout_5.addWidget(self.prev_kelas, 0, 0, 1, 1)

        self.cbo_kelas = QComboBox(self.frame_kelas)
        self.cbo_kelas.setObjectName(u"cbo_kelas")
        sizePolicy3.setHeightForWidth(self.cbo_kelas.sizePolicy().hasHeightForWidth())
        self.cbo_kelas.setSizePolicy(sizePolicy3)
        self.cbo_kelas.setMinimumSize(QSize(0, 25))
        self.cbo_kelas.setFont(font4)
        self.cbo_kelas.setMaxVisibleItems(20)

        self.gridLayout_5.addWidget(self.cbo_kelas, 1, 0, 1, 3)

        self.label_kelas = QPushButton(self.frame_kelas)
        self.label_kelas.setObjectName(u"label_kelas")
        self.label_kelas.setFont(font)

        self.gridLayout_5.addWidget(self.label_kelas, 0, 1, 1, 1)


        self.gridLayout_7.addWidget(self.frame_kelas, 0, 6, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_7.addItem(self.horizontalSpacer_2, 0, 10, 1, 1)

        self.frame_search = QWidget(self.frame_filter)
        self.frame_search.setObjectName(u"frame_search")
        sizePolicy4.setHeightForWidth(self.frame_search.sizePolicy().hasHeightForWidth())
        self.frame_search.setSizePolicy(sizePolicy4)
        self.frame_search.setMinimumSize(QSize(100, 0))
        self.frame_search.setFont(font1)
        self.frame_search.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_6 = QGridLayout(self.frame_search)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.line_search = QLineEdit(self.frame_search)
        self.line_search.setObjectName(u"line_search")
        sizePolicy3.setHeightForWidth(self.line_search.sizePolicy().hasHeightForWidth())
        self.line_search.setSizePolicy(sizePolicy3)
        self.line_search.setMinimumSize(QSize(120, 25))
        self.line_search.setMaximumSize(QSize(120, 16777215))
        self.line_search.setFont(font)
        self.line_search.setFrame(True)
        self.line_search.setClearButtonEnabled(True)

        self.gridLayout_6.addWidget(self.line_search, 1, 0, 1, 2)

        self.cbo_search_by = QComboBox(self.frame_search)
        self.cbo_search_by.setObjectName(u"cbo_search_by")
        sizePolicy3.setHeightForWidth(self.cbo_search_by.sizePolicy().hasHeightForWidth())
        self.cbo_search_by.setSizePolicy(sizePolicy3)
        self.cbo_search_by.setMinimumSize(QSize(120, 25))
        self.cbo_search_by.setMaximumSize(QSize(120, 16777215))
        self.cbo_search_by.setFont(font)
        self.cbo_search_by.setEditable(False)
        self.cbo_search_by.setFrame(False)

        self.gridLayout_6.addWidget(self.cbo_search_by, 1, 2, 1, 1)

        self.label_search = QLabel(self.frame_search)
        self.label_search.setObjectName(u"label_search")
        sizePolicy.setHeightForWidth(self.label_search.sizePolicy().hasHeightForWidth())
        self.label_search.setSizePolicy(sizePolicy)
        self.label_search.setMinimumSize(QSize(0, 20))
        font6 = QFont()
        font6.setPointSize(9)
        font6.setItalic(False)
        font6.setUnderline(False)
        self.label_search.setFont(font6)
        self.label_search.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_search.setMargin(0)
        self.label_search.setIndent(0)

        self.gridLayout_6.addWidget(self.label_search, 0, 2, 1, 1)


        self.gridLayout_7.addWidget(self.frame_search, 0, 11, 1, 1)


        self.gridLayout.addWidget(self.frame_filter, 0, 0, 1, 1)

        self.main_tab = QTabWidget(self.centralwidget)
        self.main_tab.setObjectName(u"main_tab")
        self.main_tab.setFont(font)
        self.main_tab.setTabShape(QTabWidget.Rounded)
        self.main_tab.setDocumentMode(True)
        self.main_tab.setTabsClosable(True)
        self.main_tab.setTabBarAutoHide(False)

        self.gridLayout.addWidget(self.main_tab, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1117, 21))
        self.menuSantri = QMenu(self.menuBar)
        self.menuSantri.setObjectName(u"menuSantri")
        self.menuGuru = QMenu(self.menuBar)
        self.menuGuru.setObjectName(u"menuGuru")
        self.menuSetting = QMenu(self.menuBar)
        self.menuSetting.setObjectName(u"menuSetting")
        self.menuSetting.setTearOffEnabled(False)
        self.menuNilai = QMenu(self.menuBar)
        self.menuNilai.setObjectName(u"menuNilai")
        self.menuCetak = QMenu(self.menuNilai)
        self.menuCetak.setObjectName(u"menuCetak")
        self.menuPengaturan = QMenu(self.menuNilai)
        self.menuPengaturan.setObjectName(u"menuPengaturan")
        self.menuDokumen = QMenu(self.menuBar)
        self.menuDokumen.setObjectName(u"menuDokumen")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuPreferensi_2 = QMenu(self.menuBar)
        self.menuPreferensi_2.setObjectName(u"menuPreferensi_2")
        self.menuPembayaran = QMenu(self.menuBar)
        self.menuPembayaran.setObjectName(u"menuPembayaran")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuSantri.menuAction())
        self.menuBar.addAction(self.menuGuru.menuAction())
        self.menuBar.addAction(self.menuNilai.menuAction())
        self.menuBar.addAction(self.menuDokumen.menuAction())
        self.menuBar.addAction(self.menuPembayaran.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menuPreferensi_2.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuSantri.addAction(self.actionDaftar_Kelas)
        self.menuSantri.addAction(self.actionRekap_Santri)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionMutasiMasuk)
        self.menuSantri.addAction(self.actionMutasiKeluar)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionPindah_Kelas)
        self.menuSantri.addAction(self.actionMI_ke_MD)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionKenaikan)
        self.menuSantri.addAction(self.actionKelulusan)
        self.menuSantri.addSeparator()
        self.menuSantri.addAction(self.actionCari)
        self.menuSantri.addAction(self.actionTabel)
        self.menuSantri.addSeparator()
        self.menuGuru.addAction(self.actionBukuIndukGuru)
        self.menuGuru.addAction(self.actionRiwayatKeaktifan)
        self.menuGuru.addAction(self.actionRiwayat_Mengajar)
        self.menuGuru.addAction(self.actionAdmGuru)
        self.menuSetting.addAction(self.actionInput_By_Excel)
        self.menuSetting.addAction(self.actionInput_Riwayat)
        self.menuSetting.addAction(self.actionTabelAll)
        self.menuSetting.addAction(self.actionClear_hashdata)
        self.menuNilai.addAction(self.menuPengaturan.menuAction())
        self.menuNilai.addAction(self.actionRiwayatKegiatan)
        self.menuNilai.addAction(self.actionPesertaKegiatan)
        self.menuNilai.addAction(self.actionMapelKegiatan)
        self.menuNilai.addSeparator()
        self.menuNilai.addAction(self.actionInput_Nilai)
        self.menuNilai.addSeparator()
        self.menuNilai.addAction(self.menuCetak.menuAction())
        self.menuNilai.addAction(self.actionRapor)
        self.menuNilai.addAction(self.actionRekap)
        self.menuCetak.addAction(self.actionKartu_Peserta)
        self.menuCetak.addAction(self.actionLabel_Sampul)
        self.menuPengaturan.addAction(self.actionEkskulKegiatan)
        self.menuDokumen.addAction(self.actionInput_Dokumen)
        self.menuView.addAction(self.actionShow_Filter)
        self.menuPreferensi_2.addAction(self.actionRiwayatKelas)
        self.menuPreferensi_2.addAction(self.actionAlamat)
        self.menuPreferensi_2.addAction(self.actionSekolah)
        self.menuPreferensi_2.addAction(self.actionKey_Value)
        self.menuPreferensi_2.addAction(self.actionBiaya)
        self.menuPembayaran.addAction(self.actionTransaksi_Pembayaran)
        self.menuPembayaran.addAction(self.actionRiwayat_Biaya)
        self.menuPembayaran.addAction(self.actionDispensasi)

        self.retranslateUi(MainWindow)

        self.prev_order_by.setDefault(False)
        self.next_order_by.setDefault(False)
        self.prev_tapel.setDefault(False)
        self.next_tapel.setDefault(False)
        self.next_jenjang.setDefault(False)
        self.prev_tingkat.setDefault(False)
        self.next_tingkat.setDefault(False)
        self.prev_kolom.setDefault(False)
        self.next_kolom.setDefault(False)
        self.next_kelas.setDefault(False)
        self.prev_kelas.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDaftar_Kelas.setText(QCoreApplication.translate("MainWindow", u"Daftar Kelas", None))
#if QT_CONFIG(shortcut)
        self.actionDaftar_Kelas.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionRekap_Santri.setText(QCoreApplication.translate("MainWindow", u"Rekap Santri", None))
#if QT_CONFIG(shortcut)
        self.actionRekap_Santri.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionBukuIndukGuru.setText(QCoreApplication.translate("MainWindow", u"Buku Induk Guru", None))
        self.actionPindah_Kelas.setText(QCoreApplication.translate("MainWindow", u"Pindah Kelas", None))
        self.actionMutasiKeluar.setText(QCoreApplication.translate("MainWindow", u"Keluar", None))
        self.actionMutasiMasuk.setText(QCoreApplication.translate("MainWindow", u"Masuk", None))
        self.actionKenaikan.setText(QCoreApplication.translate("MainWindow", u"Kenaikan", None))
        self.actionKelulusan.setText(QCoreApplication.translate("MainWindow", u"Kelulusan", None))
        self.actionMI_ke_MD.setText(QCoreApplication.translate("MainWindow", u"MI ke MD", None))
        self.actionTabel.setText(QCoreApplication.translate("MainWindow", u"Tabel", None))
        self.actionCari.setText(QCoreApplication.translate("MainWindow", u"Cari", None))
        self.actionRekap.setText(QCoreApplication.translate("MainWindow", u"Rekap", None))
        self.actionRapor.setText(QCoreApplication.translate("MainWindow", u"Rapor", None))
        self.actionKartu_Peserta.setText(QCoreApplication.translate("MainWindow", u"Kartu Peserta", None))
        self.actionLabel_Sampul.setText(QCoreApplication.translate("MainWindow", u"Label Sampul", None))
        self.actionRiwayatKeaktifan.setText(QCoreApplication.translate("MainWindow", u"Riwayat Keaktifan", None))
        self.actionAdmGuru.setText(QCoreApplication.translate("MainWindow", u"Adm Guru", None))
        self.actionTabelAll.setText(QCoreApplication.translate("MainWindow", u"Tabel", None))
        self.actionInput_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Input Dokumen", None))
        self.actionInput_By_Excel.setText(QCoreApplication.translate("MainWindow", u"Input By Excel", None))
        self.actionShow_Filter.setText(QCoreApplication.translate("MainWindow", u"Show Filter", None))
        self.actionInput_Riwayat.setText(QCoreApplication.translate("MainWindow", u"Input Riwayat", None))
        self.actionClear_hashdata.setText(QCoreApplication.translate("MainWindow", u"Clear hashdata", None))
        self.actionInput_Nilai.setText(QCoreApplication.translate("MainWindow", u"Input Nilai", None))
        self.actionRiwayat_Mengajar.setText(QCoreApplication.translate("MainWindow", u"Riwayat Mengajar", None))
        self.actionRiwayatKelas.setText(QCoreApplication.translate("MainWindow", u"Riwayat Kelas", None))
        self.actionAlamat.setText(QCoreApplication.translate("MainWindow", u"Alamat", None))
        self.actionSekolah.setText(QCoreApplication.translate("MainWindow", u"Sekolah", None))
        self.actionKey_Value.setText(QCoreApplication.translate("MainWindow", u"Key Value", None))
        self.actionRiwayatKegiatan.setText(QCoreApplication.translate("MainWindow", u"Riwayat Kegiatan", None))
        self.actionPesertaKegiatan.setText(QCoreApplication.translate("MainWindow", u"Peserta", None))
        self.actionMapelKegiatan.setText(QCoreApplication.translate("MainWindow", u"Mapel Kegiatan", None))
        self.actionEkskulKegiatan.setText(QCoreApplication.translate("MainWindow", u"Ekskul Kegiatan", None))
        self.actionTransaksi_Pembayaran.setText(QCoreApplication.translate("MainWindow", u"Transaksi Pembayaran", None))
        self.actionBiaya.setText(QCoreApplication.translate("MainWindow", u"Jenis Biaya", None))
        self.actionDispensasi.setText(QCoreApplication.translate("MainWindow", u"Dispensasi", None))
        self.actionRiwayat_Biaya.setText(QCoreApplication.translate("MainWindow", u"Riwayat Biaya", None))
        self.prev_order_by.setText("")
        self.label_order.setText(QCoreApplication.translate("MainWindow", u"Order", None))
        self.next_order_by.setText("")
        self.prev_tapel.setText("")
        self.next_tapel.setText("")
        self.label_tapel.setText(QCoreApplication.translate("MainWindow", u"Tapel", None))
        self.next_jenjang.setText("")
        self.label_jenjang.setText(QCoreApplication.translate("MainWindow", u"Jenjang", None))
        self.prev_tingkat.setText("")
        self.next_tingkat.setText("")
        self.label_tingkat.setText(QCoreApplication.translate("MainWindow", u"Tingkat", None))
        self.prev_kolom.setText("")
        self.label_kolom.setText(QCoreApplication.translate("MainWindow", u" Kolom", None))
        self.next_kolom.setText("")
        self.next_kelas.setText("")
        self.prev_kelas.setText("")
        self.label_kelas.setText(QCoreApplication.translate("MainWindow", u"Kelas", None))
        self.label_search.setText(QCoreApplication.translate("MainWindow", u"Search By:", None))
        self.menuSantri.setTitle(QCoreApplication.translate("MainWindow", u"Santri", None))
        self.menuGuru.setTitle(QCoreApplication.translate("MainWindow", u"Guru", None))
        self.menuSetting.setTitle(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.menuNilai.setTitle(QCoreApplication.translate("MainWindow", u"Nilai", None))
        self.menuCetak.setTitle(QCoreApplication.translate("MainWindow", u"Cetak", None))
        self.menuPengaturan.setTitle(QCoreApplication.translate("MainWindow", u"Pengaturan", None))
        self.menuDokumen.setTitle(QCoreApplication.translate("MainWindow", u"Dokumen", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuPreferensi_2.setTitle(QCoreApplication.translate("MainWindow", u"Preferensi", None))
        self.menuPembayaran.setTitle(QCoreApplication.translate("MainWindow", u"Pembayaran", None))
    # retranslateUi

