# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QComboBox,
    QGridLayout, QHBoxLayout, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QSizePolicy,
    QSpacerItem, QTabWidget, QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1318, 651)
        self.actionDaftar_Kelas = QAction(MainWindow)
        self.actionDaftar_Kelas.setObjectName(u"actionDaftar_Kelas")
        self.actionDaftar_Kelas.setCheckable(False)
        self.actionDaftar_Kelas.setChecked(False)
        self.actionRekap_Santri = QAction(MainWindow)
        self.actionRekap_Santri.setObjectName(u"actionRekap_Santri")
        self.actionBukuIndukGuru = QAction(MainWindow)
        self.actionBukuIndukGuru.setObjectName(u"actionBukuIndukGuru")
        self.actionPindah_Kelas = QAction(MainWindow)
        self.actionPindah_Kelas.setObjectName(u"actionPindah_Kelas")
        self.actionMutasiKeluar = QAction(MainWindow)
        self.actionMutasiKeluar.setObjectName(u"actionMutasiKeluar")
        self.actionMutasiMasuk = QAction(MainWindow)
        self.actionMutasiMasuk.setObjectName(u"actionMutasiMasuk")
        self.actionKenaikan = QAction(MainWindow)
        self.actionKenaikan.setObjectName(u"actionKenaikan")
        self.actionKelulusan = QAction(MainWindow)
        self.actionKelulusan.setObjectName(u"actionKelulusan")
        self.actionMI_ke_MD = QAction(MainWindow)
        self.actionMI_ke_MD.setObjectName(u"actionMI_ke_MD")
        self.actionBukuInduk = QAction(MainWindow)
        self.actionBukuInduk.setObjectName(u"actionBukuInduk")
        self.actionCari = QAction(MainWindow)
        self.actionCari.setObjectName(u"actionCari")
        self.actionRekap = QAction(MainWindow)
        self.actionRekap.setObjectName(u"actionRekap")
        self.actionRapor = QAction(MainWindow)
        self.actionRapor.setObjectName(u"actionRapor")
        self.actionKartu_Peserta = QAction(MainWindow)
        self.actionKartu_Peserta.setObjectName(u"actionKartu_Peserta")
        self.actionRiwayatKeaktifan = QAction(MainWindow)
        self.actionRiwayatKeaktifan.setObjectName(u"actionRiwayatKeaktifan")
        self.actionAdmGuru = QAction(MainWindow)
        self.actionAdmGuru.setObjectName(u"actionAdmGuru")
        self.actionTabelAll = QAction(MainWindow)
        self.actionTabelAll.setObjectName(u"actionTabelAll")
        self.actionInput_By_Excel = QAction(MainWindow)
        self.actionInput_By_Excel.setObjectName(u"actionInput_By_Excel")
        self.actionShow_Filter = QAction(MainWindow)
        self.actionShow_Filter.setObjectName(u"actionShow_Filter")
        self.actionShow_Filter.setCheckable(True)
        self.actionShow_Filter.setChecked(True)
        self.actionInput_Nilai = QAction(MainWindow)
        self.actionInput_Nilai.setObjectName(u"actionInput_Nilai")
        self.actionRiwayat_Mengajar = QAction(MainWindow)
        self.actionRiwayat_Mengajar.setObjectName(u"actionRiwayat_Mengajar")
        self.actionRiwayatKelas = QAction(MainWindow)
        self.actionRiwayatKelas.setObjectName(u"actionRiwayatKelas")
        self.actionAlamat = QAction(MainWindow)
        self.actionAlamat.setObjectName(u"actionAlamat")
        self.actionSekolah = QAction(MainWindow)
        self.actionSekolah.setObjectName(u"actionSekolah")
        self.actionRiwayatKegiatan = QAction(MainWindow)
        self.actionRiwayatKegiatan.setObjectName(u"actionRiwayatKegiatan")
        self.actionPesertaKegiatan = QAction(MainWindow)
        self.actionPesertaKegiatan.setObjectName(u"actionPesertaKegiatan")
        self.actionMapelKegiatan = QAction(MainWindow)
        self.actionMapelKegiatan.setObjectName(u"actionMapelKegiatan")
        self.actionEkskulKegiatan = QAction(MainWindow)
        self.actionEkskulKegiatan.setObjectName(u"actionEkskulKegiatan")
        self.actionTambah_Dokumen = QAction(MainWindow)
        self.actionTambah_Dokumen.setObjectName(u"actionTambah_Dokumen")
        self.actionHapus_Dokumen = QAction(MainWindow)
        self.actionHapus_Dokumen.setObjectName(u"actionHapus_Dokumen")
        self.actionLihat_Dokumen = QAction(MainWindow)
        self.actionLihat_Dokumen.setObjectName(u"actionLihat_Dokumen")
        self.actionRename_Dokumen = QAction(MainWindow)
        self.actionRename_Dokumen.setObjectName(u"actionRename_Dokumen")
        self.actionGanti_Dokumen = QAction(MainWindow)
        self.actionGanti_Dokumen.setObjectName(u"actionGanti_Dokumen")
        self.actionGanti_Dokumen.setEnabled(False)
        self.actionCompare_Dokumen = QAction(MainWindow)
        self.actionCompare_Dokumen.setObjectName(u"actionCompare_Dokumen")
        self.actionCopy_Dokumen = QAction(MainWindow)
        self.actionCopy_Dokumen.setObjectName(u"actionCopy_Dokumen")
        self.actionApp_Setting = QAction(MainWindow)
        self.actionApp_Setting.setObjectName(u"actionApp_Setting")
        self.actionApp_Setting.setEnabled(False)
        self.actionCeklis_EMIS = QAction(MainWindow)
        self.actionCeklis_EMIS.setObjectName(u"actionCeklis_EMIS")
        self.actionCeklis_VervalPD = QAction(MainWindow)
        self.actionCeklis_VervalPD.setObjectName(u"actionCeklis_VervalPD")
        self.actionExport_Excel = QAction(MainWindow)
        self.actionExport_Excel.setObjectName(u"actionExport_Excel")
        self.actionStatic_Values = QAction(MainWindow)
        self.actionStatic_Values.setObjectName(u"actionStatic_Values")
        self.actionKey_Value = QAction(MainWindow)
        self.actionKey_Value.setObjectName(u"actionKey_Value")
        self.actionDark_Mode = QAction(MainWindow)
        self.actionDark_Mode.setObjectName(u"actionDark_Mode")
        self.actionDark_Mode.setCheckable(True)
        self.actionDark_Mode.setChecked(True)
        self.action_right_panel = QAction(MainWindow)
        self.action_right_panel.setObjectName(u"action_right_panel")
        self.action_right_panel.setCheckable(True)
        icon = QIcon()
        icon.addFile(u":/dark/resources/icon/dark/right_panel.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_right_panel.setIcon(icon)
        self.action_left_panel = QAction(MainWindow)
        self.action_left_panel.setObjectName(u"action_left_panel")
        self.action_left_panel.setCheckable(True)
        self.action_left_panel.setIcon(icon)
        self.actionPrestasi = QAction(MainWindow)
        self.actionPrestasi.setObjectName(u"actionPrestasi")
        self.actionInput_Ekstrakurikuler = QAction(MainWindow)
        self.actionInput_Ekstrakurikuler.setObjectName(u"actionInput_Ekstrakurikuler")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(0, 15))
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMinimumSize(QSize(450, 28))
        self.horizontalLayout_2 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout.addWidget(self.widget_2)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.cbo_tapel = QComboBox(self.widget)
        self.cbo_tapel.setObjectName(u"cbo_tapel")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_tapel.sizePolicy().hasHeightForWidth())
        self.cbo_tapel.setSizePolicy(sizePolicy)
        self.cbo_tapel.setMinimumSize(QSize(110, 24))
        self.cbo_tapel.setMaximumSize(QSize(110, 24))
        font = QFont()
        font.setFamilies([u"Segoe UI Semibold"])
        font.setPointSize(9)
        self.cbo_tapel.setFont(font)
        self.cbo_tapel.setMaxVisibleItems(30)

        self.horizontalLayout.addWidget(self.cbo_tapel)

        self.cbo_order_by = QComboBox(self.widget)
        self.cbo_order_by.setObjectName(u"cbo_order_by")
        self.cbo_order_by.setMinimumSize(QSize(110, 24))
        self.cbo_order_by.setMaximumSize(QSize(110, 24))
        self.cbo_order_by.setFont(font)
        self.cbo_order_by.setMaxVisibleItems(30)

        self.horizontalLayout.addWidget(self.cbo_order_by)

        self.cbo_kolom = QComboBox(self.widget)
        self.cbo_kolom.setObjectName(u"cbo_kolom")
        self.cbo_kolom.setMinimumSize(QSize(110, 24))
        self.cbo_kolom.setMaximumSize(QSize(110, 24))
        self.cbo_kolom.setFont(font)
        self.cbo_kolom.setMaxVisibleItems(30)
        self.cbo_kolom.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.horizontalLayout.addWidget(self.cbo_kolom)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.frame_search = QWidget(self.widget)
        self.frame_search.setObjectName(u"frame_search")
        self.frame_search.setMinimumSize(QSize(100, 0))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.frame_search.setFont(font1)
        self.frame_search.setInputMethodHints(Qt.ImhHiddenText)
        self.gridLayout_6 = QGridLayout(self.frame_search)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setHorizontalSpacing(1)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.cbo_search_by = QComboBox(self.frame_search)
        self.cbo_search_by.setObjectName(u"cbo_search_by")
        self.cbo_search_by.setMinimumSize(QSize(100, 24))
        self.cbo_search_by.setMaximumSize(QSize(100, 24))
        font2 = QFont()
        font2.setPointSize(9)
        self.cbo_search_by.setFont(font2)
        self.cbo_search_by.setEditable(False)
        self.cbo_search_by.setFrame(False)

        self.gridLayout_6.addWidget(self.cbo_search_by, 0, 2, 1, 1)

        self.line_search = QLineEdit(self.frame_search)
        self.line_search.setObjectName(u"line_search")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.line_search.sizePolicy().hasHeightForWidth())
        self.line_search.setSizePolicy(sizePolicy1)
        self.line_search.setMinimumSize(QSize(120, 24))
        self.line_search.setMaximumSize(QSize(120, 24))
        self.line_search.setFont(font2)
        self.line_search.setFrame(True)
        self.line_search.setClearButtonEnabled(True)

        self.gridLayout_6.addWidget(self.line_search, 0, 0, 1, 2, Qt.AlignRight)

        self.btn_info = QPushButton(self.frame_search)
        self.btn_info.setObjectName(u"btn_info")
        self.btn_info.setMinimumSize(QSize(0, 22))
        icon1 = QIcon()
        icon1.addFile(u":/dark/resources/icon/dark/info.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_info.setIcon(icon1)
        self.btn_info.setIconSize(QSize(22, 22))
        self.btn_info.setFlat(True)

        self.gridLayout_6.addWidget(self.btn_info, 0, 3, 1, 1)


        self.horizontalLayout.addWidget(self.frame_search)


        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy2)
        self.gridLayout_7 = QGridLayout(self.widget_3)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.widget_4 = QWidget(self.widget_3)
        self.widget_4.setObjectName(u"widget_4")
        self.verticalLayout = QVBoxLayout(self.widget_4)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 1, 0, 0)
        self.btn_refresh = QPushButton(self.widget_4)
        self.btn_refresh.setObjectName(u"btn_refresh")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy3)
        self.btn_refresh.setMinimumSize(QSize(24, 24))
        self.btn_refresh.setMaximumSize(QSize(16777215, 24))
        font3 = QFont()
        font3.setFamilies([u"Aptos Narrow"])
        font3.setPointSize(11)
        self.btn_refresh.setFont(font3)
        icon2 = QIcon()
        icon2.addFile(u":/dark/resources/icon/dark/refresh.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_refresh.setIcon(icon2)
        self.btn_refresh.setIconSize(QSize(16, 16))

        self.verticalLayout.addWidget(self.btn_refresh)

        self.list_tingkat = QListWidget(self.widget_4)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        QListWidgetItem(self.list_tingkat)
        self.list_tingkat.setObjectName(u"list_tingkat")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.list_tingkat.sizePolicy().hasHeightForWidth())
        self.list_tingkat.setSizePolicy(sizePolicy4)
        self.list_tingkat.setMinimumSize(QSize(0, 180))
        self.list_tingkat.setMaximumSize(QSize(30, 180))
        font4 = QFont()
        font4.setFamilies([u"Aptos Narrow"])
        font4.setPointSize(10)
        self.list_tingkat.setFont(font4)
        self.list_tingkat.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_tingkat.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_tingkat.setSelectionMode(QAbstractItemView.ExtendedSelection)

        self.verticalLayout.addWidget(self.list_tingkat)

        self.list_kelas = QListWidget(self.widget_4)
        self.list_kelas.setObjectName(u"list_kelas")
        sizePolicy3.setHeightForWidth(self.list_kelas.sizePolicy().hasHeightForWidth())
        self.list_kelas.setSizePolicy(sizePolicy3)
        self.list_kelas.setMinimumSize(QSize(0, 0))
        self.list_kelas.setMaximumSize(QSize(30, 16777215))
        self.list_kelas.setFont(font4)
        self.list_kelas.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_kelas.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_kelas.setSelectionMode(QAbstractItemView.ExtendedSelection)

        self.verticalLayout.addWidget(self.list_kelas)

        self.list_jenjang = QListWidget(self.widget_4)
        QListWidgetItem(self.list_jenjang)
        QListWidgetItem(self.list_jenjang)
        self.list_jenjang.setObjectName(u"list_jenjang")
        sizePolicy3.setHeightForWidth(self.list_jenjang.sizePolicy().hasHeightForWidth())
        self.list_jenjang.setSizePolicy(sizePolicy3)
        self.list_jenjang.setMaximumSize(QSize(30, 70))
        self.list_jenjang.setFont(font4)
        self.list_jenjang.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_jenjang.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_jenjang.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.list_jenjang.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.list_jenjang.setUniformItemSizes(True)

        self.verticalLayout.addWidget(self.list_jenjang)


        self.gridLayout_7.addWidget(self.widget_4, 0, 0, 1, 1)

        self.main_tab = QTabWidget(self.widget_3)
        self.main_tab.setObjectName(u"main_tab")
        self.main_tab.setFont(font2)
        self.main_tab.setTabsClosable(True)

        self.gridLayout_7.addWidget(self.main_tab, 0, 1, 1, 1)


        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDaftar_Kelas.setText(QCoreApplication.translate("MainWindow", u"Daftar Kelas", None))
#if QT_CONFIG(shortcut)
        self.actionDaftar_Kelas.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionRekap_Santri.setText(QCoreApplication.translate("MainWindow", u"Rekap Santri", None))
#if QT_CONFIG(shortcut)
        self.actionRekap_Santri.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionBukuIndukGuru.setText(QCoreApplication.translate("MainWindow", u"Buku Induk Guru", None))
        self.actionPindah_Kelas.setText(QCoreApplication.translate("MainWindow", u"Pindah Kelas", None))
        self.actionMutasiKeluar.setText(QCoreApplication.translate("MainWindow", u"Keluar", None))
        self.actionMutasiMasuk.setText(QCoreApplication.translate("MainWindow", u"Masuk", None))
        self.actionKenaikan.setText(QCoreApplication.translate("MainWindow", u"Kenaikan", None))
        self.actionKelulusan.setText(QCoreApplication.translate("MainWindow", u"Kelulusan", None))
        self.actionMI_ke_MD.setText(QCoreApplication.translate("MainWindow", u"MI ke MD", None))
        self.actionBukuInduk.setText(QCoreApplication.translate("MainWindow", u"Buku Induk", None))
        self.actionCari.setText(QCoreApplication.translate("MainWindow", u"Cari", None))
        self.actionRekap.setText(QCoreApplication.translate("MainWindow", u"Cetak Rekap", None))
        self.actionRapor.setText(QCoreApplication.translate("MainWindow", u"Cetak Rapor", None))
        self.actionKartu_Peserta.setText(QCoreApplication.translate("MainWindow", u"Cetak Kartu Peserta", None))
        self.actionRiwayatKeaktifan.setText(QCoreApplication.translate("MainWindow", u"Riwayat Keaktifan", None))
        self.actionAdmGuru.setText(QCoreApplication.translate("MainWindow", u"Adm Guru", None))
        self.actionTabelAll.setText(QCoreApplication.translate("MainWindow", u"Tabel", None))
        self.actionInput_By_Excel.setText(QCoreApplication.translate("MainWindow", u"Input By Excel", None))
        self.actionShow_Filter.setText(QCoreApplication.translate("MainWindow", u"Show Filter", None))
        self.actionInput_Nilai.setText(QCoreApplication.translate("MainWindow", u"Input Nilai", None))
        self.actionRiwayat_Mengajar.setText(QCoreApplication.translate("MainWindow", u"Riwayat Mengajar", None))
        self.actionRiwayatKelas.setText(QCoreApplication.translate("MainWindow", u"Riwayat Kelas", None))
        self.actionAlamat.setText(QCoreApplication.translate("MainWindow", u"Alamat", None))
        self.actionSekolah.setText(QCoreApplication.translate("MainWindow", u"Sekolah", None))
        self.actionRiwayatKegiatan.setText(QCoreApplication.translate("MainWindow", u"Riwayat Kegiatan", None))
        self.actionPesertaKegiatan.setText(QCoreApplication.translate("MainWindow", u"Peserta", None))
        self.actionMapelKegiatan.setText(QCoreApplication.translate("MainWindow", u"Mapel Kegiatan", None))
        self.actionEkskulKegiatan.setText(QCoreApplication.translate("MainWindow", u"Ekskul Kegiatan", None))
        self.actionTambah_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Tambah Dokumen", None))
        self.actionHapus_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Hapus Dokumen", None))
        self.actionLihat_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Lihat Dokumen", None))
        self.actionRename_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Rename Dokumen", None))
        self.actionGanti_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Ganti Dokumen", None))
        self.actionCompare_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Bandingkan Dokumen", None))
        self.actionCopy_Dokumen.setText(QCoreApplication.translate("MainWindow", u"Copy Dokumen", None))
        self.actionApp_Setting.setText(QCoreApplication.translate("MainWindow", u"App Setting", None))
        self.actionCeklis_EMIS.setText(QCoreApplication.translate("MainWindow", u"Ceklis EMIS", None))
        self.actionCeklis_VervalPD.setText(QCoreApplication.translate("MainWindow", u"Ceklis VervalPD", None))
        self.actionExport_Excel.setText(QCoreApplication.translate("MainWindow", u"Export Excel", None))
        self.actionStatic_Values.setText(QCoreApplication.translate("MainWindow", u"Static Values", None))
        self.actionKey_Value.setText(QCoreApplication.translate("MainWindow", u"Key Value", None))
        self.actionDark_Mode.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.action_right_panel.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.action_left_panel.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.actionPrestasi.setText(QCoreApplication.translate("MainWindow", u"Input Prestasi", None))
        self.actionInput_Ekstrakurikuler.setText(QCoreApplication.translate("MainWindow", u"Input Ekstrakurikuler", None))
        self.btn_info.setText("")
        self.btn_refresh.setText("")

        __sortingEnabled = self.list_tingkat.isSortingEnabled()
        self.list_tingkat.setSortingEnabled(False)
        ___qlistwidgetitem = self.list_tingkat.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qlistwidgetitem1 = self.list_tingkat.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qlistwidgetitem2 = self.list_tingkat.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"3", None));
        ___qlistwidgetitem3 = self.list_tingkat.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"4", None));
        ___qlistwidgetitem4 = self.list_tingkat.item(4)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u"5", None));
        ___qlistwidgetitem5 = self.list_tingkat.item(5)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("MainWindow", u"6", None));
        self.list_tingkat.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.list_jenjang.isSortingEnabled()
        self.list_jenjang.setSortingEnabled(False)
        ___qlistwidgetitem6 = self.list_jenjang.item(0)
        ___qlistwidgetitem6.setText(QCoreApplication.translate("MainWindow", u"MI", None));
        ___qlistwidgetitem7 = self.list_jenjang.item(1)
        ___qlistwidgetitem7.setText(QCoreApplication.translate("MainWindow", u"MD", None));
        self.list_jenjang.setSortingEnabled(__sortingEnabled1)

    # retranslateUi

